### ISSUE TITLE
Please Consider bumping the `org.freedesktop.Platform` and `org.freedesktop.PlatformGL.default` runtime

### ISSUE THREAD

**Issue by SteveLauC** [flathub/com.wps.Office#135]
```
Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
    com.wps.Office

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
    com.wps.Office
```

**Comment by K0-RR** [comment]
Bump

**Comment by SeaDve** [comment]
I think this can be closed now via 46aaf386810d6f36592779ab8442accee626caf0.

**Comment by SteveLauC** [comment]
> I think this can be closed now via [46aaf38](https://github.com/flathub/com.wps.Office/commit/46aaf386810d6f36592779ab8442accee626caf0).

Thanks for the PR, does that PR bump org.freedesktop.PlatformGL.default as well

**Comment by SeaDve** [comment]
> Thanks for the PR, does that PR bump org.freedesktop.PlatformGL.default as well

I didn't create the PR, but I think it should also bump `org.freedesktop.PlatformGL.default` as well.

**Comment by SteveLauC** [comment]
Thanks for confirming that!

Close as completed in #133.
