### ISSUE TITLE
Allow to access to HOME

### ISSUE THREAD

**Issue by memnoth** [flathub/com.wps.Office#15]
Instead of accessing directories by each xdg, ``--filesystem=home`` would have more liberty like users can access all the directories they have in HOME dir.

**Comment by gasinvein** [comment]
In my opinion, this is way too broad access. `$HOME` contains ssh and gpg keys, and lots of data that shouldn't be available to an office sute. Also this would make escaping the sandbbox as trivial as writing to `.bashrc`.

If one wishes to grant the app access to `$HOME`, they can do so via `flatpak override --filesystem=home com.wps.Office`.

**Comment by memnoth** [comment]
It makes sense, thank you for the reply.
