### ISSUE TITLE
WPS Linux Versions

### ISSUE THREAD

**Issue by linuxosd** [flathub/com.wps.Office#153]
The WPS Office website under versions indicates 12.2 is the latest version.

The deb and rpm one can download directly from the website is 11.1 and the flatpak is also 11.1

Version 11.2 goes all the way back to 2019 and the Linux version is 11.1

Is the Linux version really that far behind, or are the Linux versions just different from the Mac and Windows version?

**Comment by madoka773** [comment]
> Is the Linux version really that far behind, or are the Linux versions just different from the Mac and Windows version?

y

**Comment by madoka773** [comment]
the new wps office only available on some linux distro for chinese gov

**Comment by bbhtt** [comment]
11.1.0.11719 seems to be the latest
