### ISSUE TITLE
version 10.1.0.6758 is available

### ISSUE THREAD

**Issue by cheese** [flathub/com.wps.Office#17]
Download URLs:
http://kdl.cc.ksosoft.com/wps-community/download/6758/wps-office_10.1.0.6758_x86_64.tar.xz
http://kdl.cc.ksosoft.com/wps-community/download/6758/wps-office_10.1.0.6758_x86.tar.xz

**Comment by gasinvein** [comment]
How did you find out about the new release? There is still 10.1.0.6757 on the [downloads page](http://wps-community.org/downloads).

**Comment by cheese** [comment]
WPS itself hints me about new release. And I found it on the Chinese page: http://www.wps.cn/product/wpslinux/#
