### ISSUE TITLE
The command flatpak run com.wps.Office.et, .wpp, and .wps not work

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.wps.Office#26]
```
erro: app/com.wps.Office.et/x86_64/master not installed
erro: app/com.wps.Office.wpp/x86_64/master not installed
erro: app/com.wps.Office.wps/x86_64/master not installed
```

**Comment by gasinvein** [comment]
It shouldn't work. `flatpak run` runs an app bundle by it's id, and WPS Office flatpak id is `com.wps.Office`.
If you want to run specific program from the bundle, use e.g. `flatpak run --command=et com.wps.Office`
