### ISSUE TITLE
Very slow download/update

### ISSUE THREAD

**Issue by alex285** [flathub/com.wps.Office#32]
As you can see in the screenshot, and it happens always
![Screenshot from 2019-04-29 16-02-45](https://user-images.githubusercontent.com/11244308/56899157-795b1c00-6a9b-11e9-8ae4-2c816d5b4252.png)

**Comment by gasinvein** [comment]
This is likely not related to flatpak. Please try to download [WPS Office package](https://github.com/flathub/com.wps.Office/blob/26f8ffb7095690bb454376850100101e2656744d/com.wps.Office.yml#L88) via wget/browser and check the speed.

**Comment by alex285** [comment]
aha! so when we pull from Flathub (eg on update), it downloads this file from its original location? so yeap, it is not a Flatpak issue, but it happens on Flathub too ..but anyway feel to close it

**Comment by gasinvein** [comment]
Yes, most of proprietary apps on Flathub are downloaded at install time from official sites.
