### ISSUE TITLE
Backup Management does not work

### ISSUE THREAD

**Issue by GoodMirek** [flathub/com.wps.Office#34]
I have just found hard way that backup management does not work in Flatpak distribution of WPS office, latest version as of today.
While installed from RPM, Backup Management works as expected.
Default backup location is /home/<user>/.kingsoft/office6/data/backup/

**Comment by gasinvein** [comment]
I didn't use the backup feature. Please provide steps to reproduce the problem.

**Comment by GoodMirek** [comment]
Please see the attached video, it shows how it works when installed from RPM.
When I instead install WPS from flathub and click click Open Backup Folder button, nothing happens. Also, nowhere on filesystem I can find autobackup files. It is especially frustrating once WPS crashes.

[simplescreenrecorder-2019-06-18_23.42.30.zip](https://github.com/flathub/com.wps.Office/files/3303553/simplescreenrecorder-2019-06-18_23.42.30.zip)

**Comment by gasinvein** [comment]
Backups should to be in `~/.var/app/com.wps.Office/.kingsoft/office6/data/backup`. Is it the case?

**Comment by GoodMirek** [comment]
Folder `~/.var/app/com.wps.Office/.kingsoft/` is empty.

**Comment by gasinvein** [comment]
This is strange. Try running `flatpak run --command=touch com.wps.Office ~/.kingsoft/new_file` and check if the file appears in `~/.var/app/com.wps.Office/.kingsoft`.

**Comment by GoodMirek** [comment]
After running the provided command `flatpak run --command=touch com.wps.Office ~/.kingsoft/new_file` I confirm that file `~/.var/app/com.wps.Office/.kingsoft/new_file` appears.

**Comment by GoodMirek** [comment]
@gasinvein Are you able to reproduce the issue?

**Comment by gasinvein** [comment]
No. Is there any way to force WPS to create a backup?

**Comment by gasinvein** [comment]
Looks like WPS changed the data location from `~/.kingsoft` to `~/.local/share/Kingsoft`.
Try running `flatpak run --persist=.local/share/Kingsoft com.wps.Office ` and check if backups (or other new data) appears in `~/.var/app/com.wps.Office/.local/share/Kingsoft`.

**Comment by GoodMirek** [comment]
I confirm that when running `flatpak run --persist=.local/share/Kingsoft com.wps.Office` then backups appear in `~/.var/app/com.wps.Office/.local/share/Kingsoft/office6/data/backup/`.
However, button Open Backup Folder still does not work.

To force WPS to create a backup, just open a file, save it, make changes, save it again.

RPM installation of WPS stores backups at `~/.kingsoft/office6/data/backup/`.

Versions:
```
rpm -q wps-office
wps-office-11.1.0.8392-1.x86_64
```

```
flatpak info com.wps.Office

WPS Office - WPS Office Suite

          ID: com.wps.Office
         Ref: app/com.wps.Office/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 11.1.0.8392
     License: LicenseRef-proprietary=http://wps-community.org/license.md
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 315.2 MB
     Runtime: org.freedesktop.Platform/x86_64/18.08
         Sdk: org.freedesktop.Sdk/x86_64/18.08

      Commit: 1e2507121382b4e41622cb4769c7c121fe66f0707eebc9906ee1b70458971cf0
      Parent: 3c3341fb5933f7cc56987009262b6f1484d24d41632dc27b82067427570b19d7
     Subject: Update wps_i18n (#31) (26f8ffb7)
        Date: 2019-04-27 12:03:15 +0000
```

**Comment by gasinvein** [comment]
>button Open Backup Folder still does not work.

It is expected, because the `~/.var/app/com.wps.Office/.local/share/Kingsoft` folder is mounted to `~/.local/share/Kingsoft` inside sandbox. WPS tries to open the later with `xdg-open`, but it doesn't exist outside sandbox.

>RPM installation of WPS stores backups at ~/.kingsoft/office6/data/backup/

Are you sure? May it be leftovers from previous version?

**Comment by GoodMirek** [comment]
>> RPM installation of WPS stores backups at ~/.kingsoft/office6/data/backup/
>
> Are you sure? May it be leftovers from previous version? Otherwise, this means that DEB (the one we use) and RPM versions of WPS Office behave differently.

I am sure new backup files appear there. Are you able to reproduce that?

**Comment by GoodMirek** [comment]
>> button Open Backup Folder still does not work.
>
> It is expected, because the ~/.var/app/com.wps.Office/.local/share/Kingsoft folder is mounted to ~/.local/share/Kingsoft inside sandbox. WPS tries to open the later with xdg-open, but it doesn't exist outside sandbox.

What is a recommended way to solve such issue for flatpaks?

**Comment by gasinvein** [comment]
>What is a recommended way to solve such issue for flatpaks?

You can pass through that folder to the sandbox via override, i.e. `flatpak override --user com.wps.Office --filesystem=~/.local/share/Kingsoft:create`.

>I am sure new backup files appear there. Are you able to reproduce that?

I'll try it later.

**Comment by gasinvein** [comment]
@GoodMirek  So I've tried installing official WPS Office RPM ( version `11.1.0.8392-1`) in a clean VM, and it does store backups in `~/.local/share/Kingsoft`. The `~/.kingsoft` directory isn't even created.

**Comment by GoodMirek** [comment]
@gasinvein I tried to delete `~/.kingsoft`. After running WPS Writer installed from RPM, opening an existing document, making a change and saving it, then I have observed that `~/.kingsoft` has been created again, with a backup file stored at `~/.kingsoft/office6/data/backup/`. I have no idea why behavior on my system differs from yours. I am using FC30 Workstation (not Silverblue).

**Comment by gasinvein** [comment]
I've found a config line explicitly setting backup location, it's `common\Backup\AutoRecoverFilePath` in `Kingsoft/Office.conf`. Probably in your case it points to `~/.kingsoft`?

**Comment by GoodMirek** [comment]
@gasinvein Yes, you are right. After deleting `~/.config/Kingsoft` my backup folder defaults to `~/.local/share/Kingsoft/office6/data/backup/`. I have validated that by using the button `Open Backup Folder`. So the root cause was configuration leftovers from before. I tried to look for Kingsoft config file in `~/.local`, did not try to look at `~/.config`.

Now, the issue is that WPS Writer does not create backups at all, but it is a different story, out of scope of this Github issue; I will try to delete the all Kingsoft related folders and reinstall the WPS office from RPM.

Thank you for all your effort and help!

**Comment by gasinvein** [comment]
So the best "solution" for this issue (with WPS flatpak) would be changing the backup location to `~/.var/app/com.wps.Office/data/Kingsoft/office6/data/backup`.
This should be done by WPS Office by default, but it ignores the `$XDG_DATA_HOME` env var, and hardcodes `~/.local/share` instead.
