### ISSUE TITLE
Wrong size for extra data

### ISSUE THREAD

**Issue by travankor** [flathub/com.wps.Office#40]
`flatpak install flathub com.wps.Office`:

Error: Wrong size for extra data http://kdl.cc.ksosoft.com/wps-community/download/8722/wps-office_11.1.0.8722_amd64.deb
error: Failed to install com.wps.Office: Wrong size for extra data http://kdl.cc.ksosoft.com/wps-community/download/8722/wps-office_11.1.0.8722_amd64.deb

**Comment by gasinvein** [comment]
Looks like the deb package was changed without bumping version/release, sha1sum specified on the download page also mismatches. This is weird.
