### ISSUE TITLE
Unusable WPS 2019 desktop file

### ISSUE THREAD

**Issue by BjoernDaase** [flathub/com.wps.Office#63]
Since a recent update a desktop file called `WPS 2019` is exported, which does not have an icon and does not work at all. When trying to run the specified exec command `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/usr/bin/wps --file-forwarding com.wps.Office @@ %F @@` you get the following output `bwrap: execvp /usr/bin/wps: No such file or directory`.

I would suggest to just remove this desktop file.

**Comment by gasinvein** [comment]
Hm, I wonder what this entry was adder for in the first place.
