### ISSUE TITLE
Formula bar white-out using a dark theme

### ISSUE THREAD

**Issue by TheRoarkster** [flathub/com.wps.Office#68]
When trying to edit a cell in `et` (i.e., spreadsheets) using a dark system theme, the formula bar is all white making it impossible to view the text.  I'm running the latest Manjaro version 20.0 and `gnome-shell` version 3.36.2.

Switching to a light system theme confirms that the formula bar works and has the correct information.

Is there a way to use WPS `et` **and** a dark system theme?

**Comment by gasinvein** [comment]
Is it reproducible with non-flatpak WPS? Also, how do you set dark system theme?

**Comment by TheRoarkster** [comment]
Yes, confirmed the issue is reproducible on non-flatpak WPS (installed from [here](https://aur.archlinux.org/packages/wps-office/)). 

Ooops, I meant dark _application_ theme (as opposed to system theme).  On any GNOME desktop, to set a dark application theme just go to `gnome-tweaks` `> Appearance > Themes > Applications` and select `Adwaita Dark`(to set a dark system theme do the same, bu .

**Comment by gasinvein** [comment]
> the issue is reproducible on non-flatpak WPS

Then it doesn't belong here and should be reported to Kingsoft. Sadly, I don't know how to contact them other than via e-mail.

**Comment by TheRoarkster** [comment]
Thanks - yeah, I appreciate that issue and understand.  I should have noted that there is a [workaround](https://github.com/horst3180/arc-theme/issues/748#issuecomment-625888933) for the non-flatpak version (which works both for the cell color and the formula bar color).  And the hope was to find one for the flatpak one.  Or maybe even have the flatpak version include it by default.

**Comment by gasinvein** [comment]
Well, you can use the same cmd arg with flatpak, e.g. `flatpak run --command=et com.wps.Office -style=motif`. Or you can set the style permanently in `~/.var/app/com.wps.Office/config/Trolltech.conf`.

**Comment by TheRoarkster** [comment]
Great.  That last location is what I was looking for.  Thank you.

**Comment by bayazidbh** [comment]
I know that this is old, but another way that I manage do it is by setting theme, color, window decoration, etc. back to Breeze Light, and then copying the kdeglobals and Trolltech.conf file from `~/.config` into `~/.var/app/com.wps.Office/config/`. You can then return the theme to whatever dark theme you were using.
