### ISSUE TITLE
32-bit download url stopped working

### ISSUE THREAD

**Issue by mama21mama** [flathub/com.wps.Office#69]
https://paste.ubuntu.com/p/dp8FJHVB8N/

`
pc@vladimir-pc:~$ sudo flatpak install flathub com.wps.Office
[sudo] password for pc: 
Looking for matches…
Required runtime for com.wps.Office/i386/stable (runtime/org.freedesktop.Platform/i386/18.08) found in remote flathub
Do you want to install it? [Y/n]: y

com.wps.Office permissions:
    ipc      network              pulseaudio      x11
    dri      file access [1]      tags [2]

    [1] /media, /run/media, xdg-documents, xdg-download, xdg-pictures,
        xdg-videos
    [2] proprietary

        ID                                    Arch Branch Remote  Descarga
 1. [✓] org.freedesktop.Platform              i386 18.08  flathub 264,6 MB / 306,7 MB
 2. [✓] org.freedesktop.Platform.Locale       i386 18.08  flathub   3,9 MB / 316,0 MB
 3. [✓] org.freedesktop.Platform.VAAPI.Intel  i386 18.08  flathub   1,9 MB / 1,9 MB
 4. [✓] org.freedesktop.Platform.html5-codecs i386 18.08  flathub   3,3 MB / 3,4 MB
 5. [✗] com.wps.Office                        i386 stable flathub 147,1 MB / 373,6 MB

Error: Mientras se descargan http://kdl.cc.ksosoft.com/wps-community/download/8392/wps-office_11.1.0.8392_i386.deb: Error al resolver «kdl.cc.ksosoft.com»: Nombre o servicio desconocido
error: Failed to instalar com.wps.Office: Mientras se descargan http://kdl.cc.ksosoft.com/wps-community/download/8392/wps-office_11.1.0.8392_i386.deb: Error al resolver «kdl.cc.ksosoft.com»: Nombre o servicio desconocido
pc@vladimir-pc:~$

`

**Comment by gasinvein** [comment]
WPS stopped to provide 32-bit builds some time ago, looks like now 32-bit downloads are unavailable.
