### ISSUE TITLE
[Open] The WPS-Office dictionary does not work in version 11.1.0.9604

### ISSUE THREAD

**Issue by serial02** [flathub/com.wps.Office#73]
Hello WPS-OFFICE Team

After installing WPS-Office, I found that the dictionaries in the selected languages are not working.
Not even adding manually to the folder.

See the gif image below:

![Screen Capture_dde-desktop_20200710230856](https://user-images.githubusercontent.com/32621790/87225662-277f7880-c365-11ea-99cb-558fee2ea5b9.gif)

The wps-office is in the correct language in PT BR, but the dictionary does not work in Brazilian Portuguese and other languages.
It also does not suggest correct words at the time of typing.

Note: In the Arch and ArcoLinux distros, where WPS-Office is installed via repositories, dictionaries of other languages also do not work.

Has anyone experienced this problem?
Is there a fix or solution for this problem?

Edson

**Comment by gasinvein** [comment]
You are not supposed to edit files of installed to flatpak app bundle. Instead, you should put dictionaries in `~/.var/app/com.wps.Office/data/Kingsoft/office6/dicts`.

**Comment by serial02** [comment]
> You are not supposed to edit files of installed to flatpak app bundle. Instead, you should put dictionaries in `~/.var/app/com.wps.Office/data/Kingsoft/office6/dicts`.

Shouldn't this happen automatically at the time of installation instead of being changed manually?

**Comment by gasinvein** [comment]
What should happen automatically? Dictionaries installation?

**Comment by serial02** [comment]
> What should happen automatically? Dictionaries installation?

Yes, following the default language of the installed Distro

**Comment by serial02** [comment]
Note that the indicated path (~ / .var / app / com.wps.Office / data / Kingsoft / office6 / dicts) the folder is empty. Not even the standard dictionary was installed in English or Chinese.

![Screen Capture_dde-file-manager_20200711121250](https://user-images.githubusercontent.com/32621790/87227249-2bfd5e80-c370-11ea-9713-58b1c2e499a2.png)

**Comment by gasinvein** [comment]
> > What should happen automatically? Dictionaries installation?
> 
> Yes, following the default language of the installed Distro

This is tricky, mostly due to the fact that most dicts lacks licence, see #5
You can create a flatpak app extension like `com.wps.Office.spellcheck.pt_BR` and submit it to flathub, see [locales](/flathub/com.wps.Office/tree/master/locales) dir for templates and instructions.


> Note that the indicated path (~ / .var / app / com.wps.Office / data / Kingsoft / office6 / dicts) the folder is empty. Not even the standard dictionary was installed in English or Chinese.

It's a per-user directory, so it's expected to be empty by default.

**Comment by serial02** [comment]
I forgot to say:

The path used for dictionaries when installing wps-office via flatpak is different, being:

/var/lib/flatpak/app/com.wps.Office/x86_64/stable/7a0da181a0eb667d87bcc643ef7119577b64475af442e54e571ab853f0d195f7/files/extra/wps-office/office6/dicts/spellcheck

**Comment by gasinvein** [comment]
As I said, you shouldn't edit files in flatpak installation (`/var/lib/flatpak`) manually.

**Comment by serial02** [comment]
> As I said, you shouldn't edit files in flatpak installation (`/var/lib/flatpak`) manually.

Not edited: This was the standard inhalation via flatpak with the exception of pt br.

**Comment by gasinvein** [comment]
Do dictionaries stored in `~/.var/app/com.wps.Office/data/Kingsoft/office6/dicts` work for you?

**Comment by serial02** [comment]
> Do dictionaries stored in `~/.var/app/com.wps.Office/data/Kingsoft/office6/dicts` work for you?

There are none (!) This appears because of the uninstallation via the deepin store. The previous wps-office version was installed and removed for installation via flatpak. This path always stays and is not the standard flatpak

**Comment by gasinvein** [comment]
Yes, there are none by default. Extract your dict (`pt_BR.zip` or so) there yourself and check if it works.
>This path always stays and is not the standard flatpak

The path `~/.var/app/com.wps.Office/data` is the user data directory for the WPS app, i.e. it contains data that's produced at run time.

**Comment by serial02** [comment]
> Yes, there are none by default. Extract your dict (`pt_BR.zip` or so) there yourself and check if it works.

I have already performed this procedure and the dictionaries in the three languages proposed in none of the mentioned distros, deepin, arc linux and arcolinuxb-deppin, updated with flatpak or not, do not work.

**Comment by gasinvein** [comment]
Wait, are saying spellcheck doesn't work at all, even in English?

**Comment by serial02** [comment]
> Wait, are saying spellcheck doesn't work at all, even in English?

I reported this since the first post

**Comment by gasinvein** [comment]
Sorry, this wasn't clear for me from your post, I assumed that manually installed extra dicts don't work.

**Comment by serial02** [comment]
> Sorry, this wasn't clear for me from your post, I assumed that manually installed extra dicts don't work.

The wps-office is in the correct language in PT BR, but the dictionary does not work in Brazilian Portuguese and other languages.
It also does not suggest correct words at the time of typing.

**Comment by serial02** [comment]
Hello WPS-Offie Team

The wps-office was updated via flatpak update on this date, but it does not inform the wps-office version or what is being updated.

In the update the following message appeared:

![Screen Capture_deepin-terminal_20200713121912](https://user-images.githubusercontent.com/32621790/87325039-52a1cd80-c507-11ea-9894-ef5df6bad0bc.png)

The updated Brazilian Portuguese dictionary remains to be installed and the other standard dictionaries do not work. The suggestion to translate while typing does not work either.

![Screen Capture_20200713123207](https://user-images.githubusercontent.com/32621790/87325094-64837080-c507-11ea-8e28-e44b3950876d.png)

The wps-office version is in Brazilian Portuguese, but it does not come with O DICIONÁRIO in PT_BR.

![Screen Capture_20200713123228](https://user-images.githubusercontent.com/32621790/87325155-79600400-c507-11ea-978d-9713626840ce.png)

Distro used Deepin UOS V20Beta

Your Considerations

Serial . com

**Comment by gasinvein** [comment]
Seems like the whole wps-community github org disappeared, so MUI and spellcheck dictionaries aren't available anymore.
