### ISSUE TITLE
Fails to Download the Deb package

### ISSUE THREAD

**Issue by Enaunimes** [flathub/com.wps.Office#82]
F: Loading http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/9662/wps-office_11.1.0.9662.XA_amd64.deb using libsoup
F: flatpak_http_should_retry_request: error: 225:24 Socket I/O timed out, n_retries_remaining: 5
F: Should retry request (remaining: 5 retries), due to transient error: Socket I/O timed out

I am able to down the deb package using my browser though.

**Comment by gasinvein** [comment]
Does it always fail for you, or just sometimes?

**Comment by Enaunimes** [comment]
It fails consistantly through different networks. I tried VPN.

**Comment by Enaunimes** [comment]
> Does it always fail for you, or just sometimes?

It fails consistantly through different networks. I tried VPN.

**Comment by gasinvein** [comment]
Consider reporting it to [flatpak bugtracker](https://github.com/flatpak/flatpak/issues), then. Since the .deb url is valid, I don't think we can fix downloading it from here.
