### ISSUE TITLE
WPS Presentation without icon

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.wps.Office#9]
![captura de tela de 2019-01-29 07-56-45](https://user-images.githubusercontent.com/26097419/51900114-36ea4c00-2393-11e9-9ab2-927dba89bce2.png)

**Comment by gasinvein** [comment]
Interesting, seems like in the app directory, contents of `export/share` differs from `files/extra/export/share` and wrong icons are exported.
Reinstalling the app fixed this for me.
